version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: valeron90/foodgram_backend:latest
    volumes:
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    env_file: .env
    depends_on:
      - db
  frontend:
    image: valeron90/foodgram_frontend:latest
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - '7000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - frontend
