# Generated by Django 3.2.3 on 2024-01-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240110_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='ingredient_in_recipes',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='recipes.recipe', verbose_name='Рецепт в корзине'),
            preserve_default=False,
        ),
    ]
