# Generated by Django 3.2.3 on 2024-01-16 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240111_1855'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag',
        ),
        migrations.AlterField(
            model_name='ingredientinrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введите положительное число')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не менее одной минуты'), django.core.validators.MaxValueValidator(1440, message='Не более 1440 минут')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='HEX формат цветового кода (#RRGGBB)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Введите корректный HEX-код цвета', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цветовой код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
