# Generated by Django 3.2.3 on 2024-01-18 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиента должно быть больше 1.'), django.core.validators.MaxValueValidator(32767, message='Введите число, не превышающее 32767')], verbose_name='Количество'),
        ),
    ]
