# Generated by Django 3.2.3 on 2024-01-20 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_shoppinglist_unique_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(db_index=True, help_text='HEX формат цветового кода (#RRGGBB)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Введите корректный HEX-код цвета в формате #RRGGBB', regex='^#(?:[0-9A-F]{3}){1,2}$')], verbose_name='Цветовой код'),
        ),
    ]
