# Generated by Django 3.2.3 on 2024-01-18 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Пароль'),
        ),
    ]
