# Generated by Django 3.2.3 on 2024-01-20 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(150)], verbose_name='Пароль'),
        ),
    ]
